name: cnn
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - cupy
  - wandb
  - tqdm
  - pytest # for testing
  - pytorch # for testing against PyTorch's implementation
  - torchvision # for testing against PyTorch's implementation